-- ===========================================================
-- CUSTOMER ANALYSIS PROJECT (PostgreSQL)
-- Database : customer_analysis
-- Table    : customer_data
-- ===========================================================

---------------------------------------------------------------
-- Q1. What is the total revenue generated by male vs. female customers?
---------------------------------------------------------------

SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY gender
ORDER BY total_revenue DESC;

---------------------------------------------------------------
-- Q2. Which customers used a discount but still spent more than
-- the average purchase amount?
---------------------------------------------------------------

SELECT
    customer_id,
    purchase_amount,
    discount_applied
FROM customer_data
WHERE discount_applied = 'Yes'
AND purchase_amount >
(
    SELECT AVG(purchase_amount)
    FROM customer_data
)
ORDER BY purchase_amount DESC;

---------------------------------------------------------------
-- Q3. Which are the top 5 products with the highest average review rating?
---------------------------------------------------------------

SELECT
    item_purchased,
    ROUND(AVG(review_rating),2) AS average_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

---------------------------------------------------------------
-- Q4. Compare the average purchase amounts between
-- Standard and Express Shipping.
---------------------------------------------------------------

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS average_purchase
FROM customer_data
GROUP BY shipping_type
ORDER BY average_purchase DESC;

---------------------------------------------------------------
-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue.
---------------------------------------------------------------

SELECT
    subscription_status,
    ROUND(AVG(purchase_amount),2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY subscription_status;

---------------------------------------------------------------
-- Q6. Which 5 products have the highest percentage of
-- purchases with discounts applied?
---------------------------------------------------------------

SELECT
    item_purchased,

    ROUND(
        SUM(
            CASE
                WHEN discount_applied='Yes' THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),2
    ) AS discount_percentage

FROM customer_data

GROUP BY item_purchased

ORDER BY discount_percentage DESC

LIMIT 5;

---------------------------------------------------------------
-- Q7. Segment customers into
-- New, Returning and Loyal
-- based on previous purchases.
---------------------------------------------------------------

SELECT

customer_id,

previous_purchases,

CASE

WHEN previous_purchases = 0 THEN 'New'

WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'

ELSE 'Loyal'

END AS customer_segment

FROM customer_data;

---------------------------------------------------------------
-- Count customers in each segment
---------------------------------------------------------------

SELECT

CASE

WHEN previous_purchases = 0 THEN 'New'

WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'

ELSE 'Loyal'

END AS customer_segment,

COUNT(*) AS total_customers

FROM customer_data

GROUP BY customer_segment

ORDER BY total_customers DESC;

---------------------------------------------------------------
-- Q8. What are the top 3 most purchased products
-- within each category?
---------------------------------------------------------------

WITH ranked_products AS
(
SELECT

category,

item_purchased,

COUNT(*) AS total_orders,

ROW_NUMBER() OVER
(
PARTITION BY category
ORDER BY COUNT(*) DESC
) AS ranking

FROM customer_data

GROUP BY category,item_purchased
)

SELECT *

FROM ranked_products

WHERE ranking <=3

ORDER BY category,ranking;

---------------------------------------------------------------
-- Q9. Are customers who are repeat buyers
-- (more than 5 previous purchases)
-- also likely to subscribe?
---------------------------------------------------------------

SELECT

subscription_status,

COUNT(*) AS total_customers,

ROUND(
COUNT(*)*100.0/
(
SELECT COUNT(*)
FROM customer_data
WHERE previous_purchases >5
),2) AS percentage

FROM customer_data

WHERE previous_purchases >5

GROUP BY subscription_status;

---------------------------------------------------------------
-- Q10. What is the revenue contribution of each age group?
---------------------------------------------------------------

SELECT

CASE

WHEN age BETWEEN 18 AND 25 THEN '18-25'

WHEN age BETWEEN 26 AND 35 THEN '26-35'

WHEN age BETWEEN 36 AND 45 THEN '36-45'

WHEN age BETWEEN 46 AND 55 THEN '46-55'

ELSE '56+'

END AS age_group,

SUM(purchase_amount) AS total_revenue

FROM customer_data

GROUP BY age_group

ORDER BY total_revenue DESC;

-- ===========================================================
-- BONUS QUERIES
-- ===========================================================

---------------------------------------------------------------
-- 1. Revenue by Category
---------------------------------------------------------------

SELECT

category,

SUM(purchase_amount) AS revenue

FROM customer_data

GROUP BY category

ORDER BY revenue DESC;

---------------------------------------------------------------
-- 2. Most Preferred Payment Method
---------------------------------------------------------------

SELECT

payment_method,

COUNT(*) AS total_transactions

FROM customer_data

GROUP BY payment_method

ORDER BY total_transactions DESC;

---------------------------------------------------------------
-- 3. Average Review Rating by Category
---------------------------------------------------------------

SELECT

category,

ROUND(AVG(review_rating),2) AS average_rating

FROM customer_data

GROUP BY category

ORDER BY average_rating DESC;

---------------------------------------------------------------
-- 4. Seasonal Revenue
---------------------------------------------------------------

SELECT

season,

SUM(purchase_amount) AS revenue

FROM customer_data

GROUP BY season

ORDER BY revenue DESC;

---------------------------------------------------------------
-- 5. Revenue by Location
---------------------------------------------------------------

SELECT

location,

SUM(purchase_amount) AS revenue

FROM customer_data

GROUP BY location

ORDER BY revenue DESC;

---------------------------------------------------------------
-- 6. Top 10 Highest Spending Customers
---------------------------------------------------------------

SELECT

customer_id,

SUM(purchase_amount) AS total_spent

FROM customer_data

GROUP BY customer_id

ORDER BY total_spent DESC

LIMIT 10;

---------------------------------------------------------------
-- 7. Average Purchase Amount by Gender
---------------------------------------------------------------

SELECT

gender,

ROUND(AVG(purchase_amount),2) AS average_purchase

FROM customer_data

GROUP BY gender;

---------------------------------------------------------------
-- 8. Average Purchase Amount by Season
---------------------------------------------------------------

SELECT

season,

ROUND(AVG(purchase_amount),2) AS average_purchase

FROM customer_data

GROUP BY season;

---------------------------------------------------------------
-- 9. Highest Selling Categories
---------------------------------------------------------------

SELECT

category,

COUNT(*) AS total_orders

FROM customer_data

GROUP BY category

ORDER BY total_orders DESC;

---------------------------------------------------------------
-- 10. Average Purchase Amount by Payment Method
---------------------------------------------------------------

SELECT

payment_method,

ROUND(AVG(purchase_amount),2) AS average_purchase

FROM customer_data

GROUP BY payment_method

ORDER BY average_purchase DESC;
